#!/usr/bin/env bash
#
## Display "Best School" 10 times.
## On the 9th iteration, display "Hi" before "Best School".
#
# Initialize counter

i=0

while ((i<10))
do
    if ((i==9))
    then
    	echo "Hi"
     fi
     echo "Best School"
     ((i++))  
done

