#!/usr/bin/env bash
#
# Display "Best School" 10 times.
# On the 9th iteration, display "Hi" before "Best School".
#
# Initialize counter

i=0

while ((i<10))
do
    if ((i==3))
    then
    	echo "bad luck"
    elif ((i==7))
    then
        echo "good luck"
    else
    	echo "Best School"
    fi
    ((i++))
done

