#!/usr/bin/env bash
# Fixes a web server to run nginx as the nginx user listening on port 8080
sed -i "s/#user www-data/user nginx/" /etc/ngix/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
